-- Seeds the 71 role names from the ASFL admin export as empty-shell sec_fabric_roles rows —
-- name only, zero sec_fabric_role_screen_grants. They do nothing on their own: asgdynamic's
-- Screen enum only covers the 10 fabric-document screens (BOOKING, BPO, RPI, WWO, PWO, GR, DO,
-- FD, FABRIC_SETUP, SECURITY_ADMIN), so most of these names (ROLE_MARKETING_MANAGER,
-- ROLE_COMMERCIAL_LC_REVISION, etc.) have no real screen to grant yet. This just pre-creates
-- the catalog so an admin can assign real Screen x Verb grants via /setup/roles later, without
-- guessing what each name should actually permit.
--
-- APPLY THIS BY HAND — same caveat as V7-V10.
--
-- Idempotent — safe to re-run.

INSERT INTO sec_fabric_roles (name, description, active, created_by, created_at)
SELECT r.name, '', TRUE, 'seed', NOW()
FROM (VALUES
    ('ROLE_ACCOUNTS'), ('ROLE_ADMIN'), ('ROLE_ADMINISTRATOR'), ('ROLE_APPROVAL'),
    ('ROLE_BANK_SETUP'), ('ROLE_BOOKING_REPORT'), ('ROLE_BOOKING_REVISION'),
    ('ROLE_CI_APPROVAL'), ('ROLE_CI_CHECKER'), ('ROLE_CI_ISSUE_VIEW'), ('ROLE_CI_MAKER'),
    ('ROLE_COMMERCIAL'), ('ROLE_COMMERCIAL_CI_ISSUE'), ('ROLE_COMMERCIAL_CI_REPORT'),
    ('ROLE_COMMERCIAL_CI_REVISION'), ('ROLE_COMMERCIAL_DOCUMENT_NAMES'),
    ('ROLE_COMMERCIAL_LC_COST_HEAD'), ('ROLE_COMMERCIAL_LC_RECEIVING'),
    ('ROLE_COMMERCIAL_LC_REPORT'), ('ROLE_COMMERCIAL_LC_REVISION'),
    ('ROLE_COMMERCIAL_LC_TERMS_&_CONDITIONS'), ('ROLE_COMMERCIAL_PI_ISSUE'),
    ('ROLE_COMMERCIAL_PI_REPORT'), ('ROLE_COMMERCIAL_PI_REVISION'),
    ('ROLE_COMMERCIAL_PI_TERMS_&_CONDITIONS'), ('ROLE_COMMERCIAL_SETUP'),
    ('ROLE_DELIVERY_ORDER'), ('ROLE_DELIVERY_ORDER_REPORT_LIST'),
    ('ROLE_DELIVERY_ORDER_REQUEST'), ('ROLE_EMPLOYEE'), ('ROLE_FABRICS_DELIVERY'),
    ('ROLE_FABRICS_DELIVERY_REPORT_LIST'), ('ROLE_FINISHED_GOODS_TRANSACTION'),
    ('ROLE_GREIGE_FABRICS_TRANSACTION'), ('ROLE_HRM'), ('ROLE_IMPORT_MAKER'),
    ('ROLE_IMPORT_MANAGER'), ('ROLE_IMPORT_SETUP'), ('ROLE_INVENTORY'),
    ('ROLE_LC_APPROVAL'), ('ROLE_LC_CHECKER'), ('ROLE_LC_MAKER'),
    ('ROLE_MARKETING_ADMIN'), ('ROLE_MARKETING_EXECUTIVE'), ('ROLE_MARKETING_MANAGER'),
    ('ROLE_MARKETING_TEAMLEAD'), ('ROLE_OPEN_API'), ('ROLE_PI_APPROVAL'),
    ('ROLE_PI_CHECKER'), ('ROLE_PI_MAKER'), ('ROLE_PLANNING'), ('ROLE_PLANNING_HEAD'),
    ('ROLE_PROCESSING_STORE'), ('ROLE_PRODUCTION'), ('ROLE_PRODUCTION_DELIVERY_SCHEDULE'),
    ('ROLE_PRODUCTION_ORDER'), ('ROLE_PRODUCTION_ORDER_REPORT_LIST'),
    ('ROLE_PRODUCTION_ORDER_REQUIREMENT'), ('ROLE_PRODUCTION_ORDER_REVISION'),
    ('ROLE_PURCHASE'), ('ROLE_REPORT'), ('ROLE_RND'),
    ('ROLE_ROLE_ADMIN_IMPORT_COMMERCIAL'), ('ROLE_SALES'),
    ('ROLE_SALES_&_MARKETING_SETUP'), ('ROLE_SERVICE'), ('ROLE_SETUP'),
    ('ROLE_SOLID_DYED_BOOKING'), ('ROLE_SUPER_ADMIN'), ('ROLE_WEAVING_STORE'),
    ('ROLE_YARN_DYED_BOOKING')
) AS r(name)
WHERE NOT EXISTS (SELECT 1 FROM sec_fabric_roles sr WHERE sr.name = r.name);
