-- ---------------------------------------------------------------------------
-- Core document model.
--
-- Written by hand, not generated by Hibernate. The live SpindleERP schema grew under
-- ddl-auto=update, which creates foreign keys but never indexes them: 194 of its 327
-- foreign keys have no supporting index. That is harmless at a few hundred rows and
-- expensive at production volume, because PostgreSQL must sequential-scan every child
-- table to validate a parent DELETE. Every FK below is indexed at creation.
-- ---------------------------------------------------------------------------

-- Document number counter. One row per (tenant, {TYPE}{UNIT}) pair.
CREATE TABLE gbl_document_sequence (
    organization_id BIGINT      NOT NULL,
    seq_key         VARCHAR(32) NOT NULL,
    last_value      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_gbl_document_sequence PRIMARY KEY (organization_id, seq_key)
);

COMMENT ON TABLE gbl_document_sequence IS
    'Per (tenant, document type + business unit) counter. Seed from the legacy high-water '
    'mark before go-live or numbers already in circulation will be reissued.';

-- ---------------------------------------------------------------------------
-- Documents
-- ---------------------------------------------------------------------------
CREATE TABLE gbl_business_documents (
    id                  BIGSERIAL    PRIMARY KEY,
    organization_id     BIGINT       NOT NULL,
    document_no         VARCHAR(60)  NOT NULL,
    reference_no        VARCHAR(100),
    document_type       VARCHAR(40)  NOT NULL,
    status              VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
    business_unit_id    BIGINT       NOT NULL,
    warehouse_id        BIGINT,
    document_date       DATE         NOT NULL,
    required_date       DATE,
    party_id            BIGINT,
    parent_document_id  BIGINT,
    currency_code       VARCHAR(3)   NOT NULL DEFAULT 'BDT',
    exchange_rate       NUMERIC(18,6) NOT NULL DEFAULT 1,
    revision_no         INTEGER      NOT NULL DEFAULT 0,
    revision_of_id      BIGINT,
    remarks             VARCHAR(1000),
    subtotal_amount     NUMERIC(20,6) NOT NULL DEFAULT 0,
    total_quantity      NUMERIC(20,6) NOT NULL DEFAULT 0,
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    version             BIGINT,
    created_by          VARCHAR(100),
    created_at          TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMP,

    CONSTRAINT uk_gbd_org_document_no UNIQUE (organization_id, document_no),
    CONSTRAINT fk_gbd_parent      FOREIGN KEY (parent_document_id) REFERENCES gbl_business_documents (id),
    CONSTRAINT fk_gbd_revision_of FOREIGN KEY (revision_of_id)     REFERENCES gbl_business_documents (id),
    CONSTRAINT ck_gbd_revision    CHECK (revision_no >= 0),
    -- A revision must point at something; an original must not point at itself.
    CONSTRAINT ck_gbd_revision_lineage CHECK (
        (revision_no = 0 AND revision_of_id IS NULL) OR
        (revision_no > 0 AND revision_of_id IS NOT NULL AND revision_of_id <> id)
    )
);

-- Indexes for both foreign keys above, plus the access paths the list screens use.
CREATE INDEX ix_gbd_parent        ON gbl_business_documents (parent_document_id);
CREATE INDEX ix_gbd_revision_of   ON gbl_business_documents (revision_of_id);
CREATE INDEX ix_gbd_org_type_status ON gbl_business_documents (organization_id, document_type, status);
CREATE INDEX ix_gbd_org_unit_date   ON gbl_business_documents (organization_id, business_unit_id, document_date);
CREATE INDEX ix_gbd_party         ON gbl_business_documents (party_id);
CREATE INDEX ix_gbd_document_date ON gbl_business_documents (document_date);

-- Soft-deleted rows are never listed; keep them out of the hot index.
CREATE INDEX ix_gbd_live ON gbl_business_documents (organization_id, document_type, document_date)
    WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- Document lines (fabric identity embedded)
-- ---------------------------------------------------------------------------
CREATE TABLE gbl_business_document_lines (
    id                    BIGSERIAL    PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    document_id           BIGINT       NOT NULL,
    line_no               INTEGER      NOT NULL DEFAULT 0,
    item_id               BIGINT,
    uom_id                BIGINT,

    -- FabricSpec (embedded)
    construction          VARCHAR(60),
    declared_construction VARCHAR(60),
    weave_type            VARCHAR(60),
    weave_style           VARCHAR(60),
    fabric_type           VARCHAR(60),
    finish_type           VARCHAR(60),
    composition           VARCHAR(120),
    gsm                   NUMERIC(12,4),
    finish_width          NUMERIC(12,4),
    cuttable_width        NUMERIC(12,4),
    light_source          VARCHAR(30),
    selvedge              VARCHAR(40),
    colour_code           VARCHAR(40),
    colour_name           VARCHAR(120),
    costing_code          VARCHAR(40),

    quantity              NUMERIC(20,6) NOT NULL DEFAULT 0,
    rate                  NUMERIC(20,6) NOT NULL DEFAULT 0,
    fulfilled_quantity    NUMERIC(20,6) NOT NULL DEFAULT 0,
    line_amount           NUMERIC(20,6) NOT NULL DEFAULT 0,
    remarks               VARCHAR(500),
    version               BIGINT,
    created_by            VARCHAR(100),
    created_at            TIMESTAMP,
    updated_by            VARCHAR(100),
    updated_at            TIMESTAMP,

    CONSTRAINT fk_gbdl_document FOREIGN KEY (document_id)
        REFERENCES gbl_business_documents (id) ON DELETE CASCADE,
    CONSTRAINT ck_gbdl_quantity   CHECK (quantity >= 0),
    CONSTRAINT ck_gbdl_rate       CHECK (rate >= 0),
    -- The database enforces the fulfilment ceiling too, not just the domain model.
    CONSTRAINT ck_gbdl_fulfilment CHECK (fulfilled_quantity >= 0 AND fulfilled_quantity <= quantity)
);

CREATE INDEX ix_gbdl_document ON gbl_business_document_lines (document_id);
CREATE INDEX ix_gbdl_item     ON gbl_business_document_lines (item_id);
CREATE INDEX ix_gbdl_org      ON gbl_business_document_lines (organization_id);

-- Open-order queries ("what is still outstanding") hit this constantly.
CREATE INDEX ix_gbdl_outstanding ON gbl_business_document_lines (document_id)
    WHERE fulfilled_quantity < quantity;

-- Costing lookups back from a line to the external costing system.
CREATE INDEX ix_gbdl_costing_code ON gbl_business_document_lines (costing_code)
    WHERE costing_code IS NOT NULL;
